class RiveObj {
  final String resId;
  final String? stateMachineName;
  final String? artboardName;

  RiveObj(this.resId, {this.stateMachineName, this.artboardName});
}

final List<RiveObj> riveObjects = [
  RiveObj('assets/soarus.riv', stateMachineName: "DinoMove!"),
  RiveObj('assets/dragon_ride.riv', stateMachineName: "State Machine 1"),
  RiveObj('assets/panda.riv',
      artboardName: "normal way", stateMachineName: "State Machine 1"),
  RiveObj('assets/walk_boom.riv', stateMachineName: "State Machine 1"),
  RiveObj('assets/ori.riv', stateMachineName: "State Machine 1"),
  RiveObj('assets/guitargirl.riv', stateMachineName: "State Machine 1"),
  RiveObj('assets/dog_escape.riv', stateMachineName: "State Machine 1"),
  RiveObj('assets/alien.riv', stateMachineName: "State Machine 1"),
  RiveObj('assets/walk_cycle_blend.riv',
      artboardName: 'combined', stateMachineName: "State Machine 1"),
  RiveObj('assets/testjoystickplanet.riv', stateMachineName: "Dance"),
  RiveObj('assets/pencil_dude_hello.riv'),
  RiveObj('assets/artist.riv', artboardName: 'Artist Comp'),
  RiveObj('assets/big_wheel_demo.riv', stateMachineName: "State Machine 1"),
  RiveObj('assets/chatbot.riv', stateMachineName: "State Machine 1"),
  RiveObj('assets/_2d_girl.riv',
      artboardName: '2dGirl', stateMachineName: "State Machine 1"),
  RiveObj('assets/luke_vs_darth.riv'),
  RiveObj('assets/flying.riv'),
  RiveObj('assets/spacecow.riv', stateMachineName: "State Machine 1"),
  RiveObj('assets/smileys.riv', stateMachineName: "controller"),
  RiveObj('assets/cat.riv'),
  RiveObj('assets/football_time.riv', stateMachineName: "State Machine 1"),
  RiveObj('assets/walle.riv', stateMachineName: "State Machine 1"),
  RiveObj('assets/game_character_demo.riv'),
  RiveObj('assets/sketis.riv',
      artboardName: "Sketis", stateMachineName: "State Machine 1"),
  RiveObj('assets/donnie_the_dino.riv', stateMachineName: "State Machine 1"),
  RiveObj('assets/flame_and_spark.riv'),
  RiveObj('assets/thats_no_moon.riv'),
  RiveObj('assets/anime_girl.riv', stateMachineName: "State Machine 1"),
  RiveObj('assets/pull_to_refresh_.riv'),
  RiveObj('assets/bat.riv', stateMachineName: "State Machine 1"),
  RiveObj('assets/floaty_boi.riv'),
  RiveObj('assets/zoom_loop_nested_artboards_example.riv'),
  RiveObj('assets/happy_little_robot.riv', stateMachineName: "State Machine 1"),
  RiveObj('assets/book.riv'),
  RiveObj('assets/mech_publish.riv', stateMachineName: "walkStateMachine"),
  RiveObj('assets/robot_puppet.riv'),
  RiveObj('assets/castle_demo.riv'),
  RiveObj('assets/juicy_walk.riv'),
  RiveObj('assets/knight.riv'),
  RiveObj('assets/doggo.riv'),
  RiveObj('assets/paint.riv'),
  RiveObj('assets/girl_black_hair.riv'),
  RiveObj('assets/truck.riv', stateMachineName: "drive"),
  RiveObj('assets/rigging_a_character.riv',
      stateMachineName: "State Machine 1"),
  RiveObj('assets/polito.riv', stateMachineName: "State Machine 1"),
  RiveObj('assets/hero_use_case.riv', stateMachineName: "State Machine 1"),
  RiveObj('assets/mixing_animations.riv', stateMachineName: "State Machine 1"),
  RiveObj('assets/login_screen_character.riv',
      stateMachineName: "State Machine 1"),
  RiveObj('assets/gost.riv', stateMachineName: "State Machine 1"),
  RiveObj('assets/game_controller.riv', stateMachineName: "State Machine 1"),
];
